### ISSUE TITLE
problems after install

### ISSUE THREAD

**Issue by Spica2** [outflux3/AdminHelp#1]
after installing with pw 2.7.2 I have this issiu

Notice: Undefined index: setupYN in /Applications/MAMP/htdocs/ProcessWire/site/modules/AdminHelp/AdminHelp.module on line 44

Warning: Cannot modify header information - headers already sent by (output started at /Applications/MAMP/htdocs/ProcessWire/site/modules/AdminHelp/AdminHelp.module:44) in /Applications/MAMP/htdocs/ProcessWire/wire/core/admin.php on line 16

Pages tab is not accessable anymore

Uninstalling:
Notice: Undefined index: setupYN in /Applications/MAMP/htdocs/ProcessWire/site/modules/AdminHelp/AdminHelp.module on line 44

Warning: Cannot modify header information - headers already sent by (output started at /Applications/MAMP/htdocs/ProcessWire/site/modules/AdminHelp/AdminHelp.module:44) in /Applications/MAMP/htdocs/ProcessWire/wire/core/admin.php on line 16

Notice: Undefined index: setupYN in /Applications/MAMP/htdocs/ProcessWire/site/modules/AdminHelp/AdminHelp.module on line 44

Warning: Cannot modify header information - headers already sent by (output started at /Applications/MAMP/htdocs/ProcessWire/site/modules/AdminHelp/AdminHelp.module:44) in /Applications/MAMP/htdocs/ProcessWire/wire/core/Session.php on line 617

Warning: Cannot modify header information - headers already sent by (output started at /Applications/MAMP/htdocs/ProcessWire/site/modules/AdminHelp/AdminHelp.module:44) in /Applications/MAMP/htdocs/ProcessWire/wire/core/Session.php on line 618

**Comment by outflux3** [comment]
ok thanks, i will fix that - were you able to uninstall it successfully?

**Comment by outflux3** [comment]
I just commited a change that adds a check if the variable is populated, which is how it is supposed to be, but i'm not seeing the error either way, so can you tell me if that fixes it? otherwise i will try and see if i can get error reporting on; 
can you tell me which PHP version you are using and which admin theme?
also, those notices and warnings shouldn't stop it from working - the notice is probably causing the warning;

**Comment by Spica2** [comment]
php 5.6.10

with new version the problem is gone.

But had a hard time to re-install. Templates and fields were not fully installed after my first failure. Simple reinstall did not succeed. So I returned to my last dump, but:
Fatal error: Exception: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'field_template_select' already exists (in /Applications/MAMP/htdocs/ProcessWire/wire/core/Fieldtype.php line 554) #0 /Applications/MAMP/htdocs/ProcessWire/wire/core/Fieldtype.php(554): PDOStatement->execute() #1 [internal function]: Fieldtype->___createField(Object(Field)) #2 /Applications/MAMP/htdocs/ProcessWire/wire/core/Wire.php(398): call_user_func_array(Array, Array) #3 /Applications/MAMP/htdocs/ProcessWire/wire/core/Wire.php(333): Wire->runHooks('createField', Array) #4 /Applications/MAMP/htdocs/ProcessWire/wire/core/Fields.php(169): Wire->__call('createField', Array) #5 /Applications/MAMP/htdocs/ProcessWire/wire/core/Fields.php(169): FieldtypeTemplates->createField(Object(Field)) #6 [internal function]: Fields->___save(Object(Field)) #7 /Applications/MAMP/htdocs/ProcessWire/wire/core/Wire.php(398): call_user_func_array(Array, Array) #8 /Applicat in /Applications/MAMP/htdocs/ProcessWire/index.php on line 248

After some reinstall iterations manually deleted field_template_select and reinstalled. 
Furthermore:  AdminHelp: No body field was found, please add manually. Yes, I had no body field. Maby an explicite own text field would be better than to rely on preinstalls to get the propper impression how this module is meant to be.

Would also recommend to add the 'icon'     => 'life-ring' to processAdminHelp.module

**Comment by outflux3** [comment]
ok thanks again for the reports; 

i guess i need to fix the code to better check for the existence of the fields, templates and pages, i'm not sure if my conditions for checking those are correct, so i will work on that - i guess that is why the problem is happening (?), so i'll test a lot more and see if it has errors when running setup when any of those items already exists

about the body field, so i guess i could check to see if there is an existing body field and then if none i could create a ckeditor field called help_body and tell the module to use that for the help-doc template.

I have added the icons to the sub-modules, thanks for the advice;
